apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
name: observability
namespace: argocd
spec:
description: Observability & reliability tooling
sourceRepos:
- "https://github.com/your-org/*"
destinations:
- namespace: robusta
server: https://kubernetes.default.svc
clusterResourceWhitelist:
- group: "*"
kind: "*"
