# Namespace for monitoring stack
apiVersion: v1
kind: Namespace
metadata:
  name: robusta
  labels:
    app.kubernetes.io/name: monitoring
    app.kubernetes.io/component: namespace
---
# ResourceQuota for the namespace
apiVersion: v1
kind: ResourceQuota
metadata:
  name: monitoring-quota
  namespace: robusta
spec:
  hard:
    requests.cpu: "4"
    requests.memory: 8Gi
    limits.cpu: "8"
    limits.memory: 16Gi
    persistentvolumeclaims: "10"
---
# LimitRange for default resource limits
apiVersion: v1
kind: LimitRange
metadata:
  name: monitoring-limits
  namespace: robusta
spec:
  limits:
    - default:
        cpu: 500m
        memory: 512Mi
      defaultRequest:
        cpu: 100m
        memory: 128Mi
      type: Container
---
# Network Policy - allow ingress from monitoring components
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: monitoring-network-policy
  namespace: robusta
spec:
  podSelector: {}
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              app.kubernetes.io/name: monitoring
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: kube-system
        - podSelector: {}
  egress:
    - {}  # Allow all egress (needed for remote write, notifications)
