# =============================================================================
# External Secrets Configuration
# =============================================================================
# This integrates with External Secrets Operator to pull secrets from
# AWS Secrets Manager, HashiCorp Vault, Azure Key Vault, etc.
# =============================================================================

# First, deploy External Secrets Operator:
# helm install external-secrets external-secrets/external-secrets -n external-secrets --create-namespace

---
# ClusterSecretStore for AWS Secrets Manager
# (Uncomment and configure for your secret backend)
# apiVersion: external-secrets.io/v1beta1
# kind: ClusterSecretStore
# metadata:
#   name: aws-secretsmanager
# spec:
#   provider:
#     aws:
#       service: SecretsManager
#       region: us-east-1
#       auth:
#         jwt:
#           serviceAccountRef:
#             name: external-secrets-sa
#             namespace: external-secrets

---
# ClusterSecretStore for HashiCorp Vault
# apiVersion: external-secrets.io/v1beta1
# kind: ClusterSecretStore
# metadata:
#   name: vault-backend
# spec:
#   provider:
#     vault:
#       server: "https://vault.example.com"
#       path: "secret"
#       version: "v2"
#       auth:
#         kubernetes:
#           mountPath: "kubernetes"
#           role: "external-secrets"

---
# ExternalSecret for Robusta credentials
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: robusta-secrets
  namespace: robusta
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secretsmanager  # or vault-backend
    kind: ClusterSecretStore
  target:
    name: robusta-credentials
    creationPolicy: Owner
    template:
      type: Opaque
      data:
        # Robusta configuration
        signing_key: "{{ .signing_key }}"
        account_id: "{{ .account_id }}"
        robusta_token: "{{ .robusta_token }}"
        
        # Slack
        slack_api_key: "{{ .slack_api_key }}"
        
        # PagerDuty
        pagerduty_routing_key: "{{ .pagerduty_routing_key }}"
        
        # Grafana
        grafana_admin_password: "{{ .grafana_admin_password }}"
  data:
    - secretKey: signing_key
      remoteRef:
        key: k3s-monitoring/robusta
        property: signing_key
    - secretKey: account_id
      remoteRef:
        key: k3s-monitoring/robusta
        property: account_id
    - secretKey: robusta_token
      remoteRef:
        key: k3s-monitoring/robusta
        property: robusta_token
    - secretKey: slack_api_key
      remoteRef:
        key: k3s-monitoring/slack
        property: api_key
    - secretKey: pagerduty_routing_key
      remoteRef:
        key: k3s-monitoring/pagerduty
        property: routing_key
    - secretKey: grafana_admin_password
      remoteRef:
        key: k3s-monitoring/grafana
        property: admin_password

---
# Alternative: Sealed Secrets (for GitOps without external secret store)
# Install: helm install sealed-secrets sealed-secrets/sealed-secrets -n kube-system
#
# Create sealed secret:
# kubectl create secret generic robusta-credentials \
#   --from-literal=signing_key=xxx \
#   --from-literal=account_id=xxx \
#   --dry-run=client -o yaml | \
#   kubeseal --format yaml > sealed-robusta-secrets.yaml

---
# Manual Secret Template (for development/testing only - DO NOT commit real values)
apiVersion: v1
kind: Secret
metadata:
  name: robusta-credentials-template
  namespace: robusta
  annotations:
    description: "TEMPLATE ONLY - Use External Secrets or Sealed Secrets in production"
type: Opaque
stringData:
  signing_key: "REPLACE_ME"
  account_id: "REPLACE_ME"
  robusta_token: "REPLACE_ME"
  slack_api_key: "xoxb-REPLACE_ME"
  pagerduty_routing_key: "REPLACE_ME"
  grafana_admin_password: "REPLACE_ME"
