apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
name: robusta
namespace: argocd
spec:
project: observability
source:
repoURL: https://github.com/your-org/robusta-gitops
targetRevision: main
path: helm/robusta
helm:
valueFiles:
- ../../environments/prod/robusta-values.yaml
destination:
server: https://kubernetes.default.svc
namespace: robusta
syncPolicy:
automated:
prune: true
selfHeal: true
syncOptions:
- CreateNamespace=true
