# =============================================================================
# Robusta - Intelligent Kubernetes Alerting
# =============================================================================
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: robusta
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://robusta-charts.storage.googleapis.com
    chart: robusta
    targetRevision: 0.12.*  # Pin to minor version for stability
    helm:
      releaseName: robusta
      # Values from Git repository
      valueFiles:
        - $values/base/robusta/values.yaml
        - $values/overlays/prod/robusta-values.yaml
  sources:
    # Primary source - Helm chart
    - repoURL: https://robusta-charts.storage.googleapis.com
      chart: robusta
      targetRevision: 0.12.*
      helm:
        releaseName: robusta
        valueFiles:
          - $values/base/robusta/values.yaml
          - $values/overlays/prod/robusta-values.yaml
    # Secondary source - Values from Git
    - repoURL: https://github.com/YOUR_ORG/k3s-monitoring.git
      targetRevision: HEAD
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: robusta
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
    retry:
      limit: 5
      backoff:
        duration: 10s
        factor: 2
        maxDuration: 5m
  ignoreDifferences:
    - group: ""
      kind: Secret
      jsonPointers:
        - /data
    - group: admissionregistration.k8s.io
      kind: ValidatingWebhookConfiguration
      jqPathExpressions:
        - .webhooks[]?.clientConfig.caBundle
    - group: admissionregistration.k8s.io
      kind: MutatingWebhookConfiguration
      jqPathExpressions:
        - .webhooks[]?.clientConfig.caBundle
