# =============================================================================
# ArgoCD App-of-Apps Pattern
# =============================================================================
# This is the root application that manages all monitoring components.
# Deploy this first: kubectl apply -f apps/root-app.yaml
# =============================================================================

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: k3s-monitoring
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/YOUR_ORG/k3s-monitoring.git  # Change to your repo
    targetRevision: HEAD
    path: apps
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
